using System.Globalization;
using System.Net;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using WinAppInspector.Core.Models;

namespace WinAppInspector.Analysis.Export;

public enum ReportFormat
{
    Csv = 0,
    Json = 1,
    Html = 2,
}

/// <summary>Column headings and value labels, supplied by the UI so the report is in the user's language.</summary>
public sealed record ReportLabels
{
    public string Title { get; init; } = "WinApp Inspector report";
    public string Name { get; init; } = "Name";
    public string Version { get; init; } = "Version";
    public string Publisher { get; init; } = "Publisher";
    public string Type { get; init; } = "Type";
    public string InstallLocation { get; init; } = "Install location";
    public string Status { get; init; } = "Status";
    public string IsRunning { get; init; } = "Running";
    public string UninstallMethod { get; init; } = "Uninstall method";
    public string DiskUsage { get; init; } = "Disk usage";
    public string Yes { get; init; } = "Yes";
    public string No { get; init; } = "No";
    public string ScanTime { get; init; } = "Scan time";
    public string GeneratedBy { get; init; } = "Generated by WinApp Inspector";
    public Func<AppType, string> TypeText { get; init; } = t => t.ToString();
    public Func<UninstallMethod, string> UninstallMethodText { get; init; } = m => m.ToString();
    public Func<ApplicationEntity, string> StatusText { get; init; } = a => a.IsRunning ? "Running" : a.AppType.ToString();
    public Func<long?, string> SizeText { get; init; } = b => b is null ? string.Empty : b.Value.ToString(CultureInfo.InvariantCulture);
}

/// <summary>One report line (§44): the fields a user needs to rebuild a software list before reinstalling.</summary>
public sealed record ReportRow(
    string Name,
    string? Version,
    string? Publisher,
    string Type,
    string? InstallLocation,
    string Status,
    bool IsRunning,
    string UninstallMethod,
    long? DiskUsageBytes,
    string? DiskUsageText);

/// <summary>Writes the software list as CSV, JSON or a self-contained HTML page (§44). Pure string generation; the caller saves the file.</summary>
public static class ReportExporter
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public static IReadOnlyList<ReportRow> ToRows(IEnumerable<ApplicationEntity> applications, ReportLabels labels)
    {
        ArgumentNullException.ThrowIfNull(applications);
        ArgumentNullException.ThrowIfNull(labels);

        return applications.Select(a => new ReportRow(
            a.Name,
            a.Version,
            a.Publisher,
            labels.TypeText(a.AppType),
            a.InstallLocation,
            labels.StatusText(a),
            a.IsRunning,
            a.HasOfficialUninstaller ? labels.UninstallMethodText(a.PreferredUninstallMethod) : labels.UninstallMethodText(UninstallMethod.None),
            a.DiskUsageBytes ?? a.EstimatedSizeBytes,
            labels.SizeText(a.DiskUsageBytes ?? a.EstimatedSizeBytes))).ToArray();
    }

    public static string Export(IEnumerable<ApplicationEntity> applications, ReportFormat format, ReportLabels labels, DateTimeOffset scanTime)
    {
        var rows = ToRows(applications, labels);
        return format switch
        {
            ReportFormat.Csv => ToCsv(rows, labels),
            ReportFormat.Json => ToJson(rows, labels, scanTime),
            ReportFormat.Html => ToHtml(rows, labels, scanTime),
            _ => throw new ArgumentOutOfRangeException(nameof(format), format, null),
        };
    }

    /// <summary>RFC 4180 CSV with a UTF-8 BOM so Excel opens Chinese text correctly.</summary>
    public static string ToCsv(IReadOnlyList<ReportRow> rows, ReportLabels labels)
    {
        ArgumentNullException.ThrowIfNull(rows);
        ArgumentNullException.ThrowIfNull(labels);

        var sb = new StringBuilder();
        sb.Append('﻿');
        AppendCsvLine(sb, [labels.Name, labels.Version, labels.Publisher, labels.Type, labels.InstallLocation, labels.Status, labels.IsRunning, labels.UninstallMethod, labels.DiskUsage]);
        foreach (var r in rows)
        {
            AppendCsvLine(sb, [r.Name, r.Version, r.Publisher, r.Type, r.InstallLocation, r.Status, r.IsRunning ? labels.Yes : labels.No, r.UninstallMethod, r.DiskUsageText]);
        }

        return sb.ToString();
    }

    public static string ToJson(IReadOnlyList<ReportRow> rows, ReportLabels labels, DateTimeOffset scanTime)
    {
        ArgumentNullException.ThrowIfNull(rows);
        ArgumentNullException.ThrowIfNull(labels);

        var document = new
        {
            title = labels.Title,
            scanTime,
            generatedBy = labels.GeneratedBy,
            count = rows.Count,
            applications = rows,
        };
        return JsonSerializer.Serialize(document, JsonOptions);
    }

    public static string ToHtml(IReadOnlyList<ReportRow> rows, ReportLabels labels, DateTimeOffset scanTime)
    {
        ArgumentNullException.ThrowIfNull(rows);
        ArgumentNullException.ThrowIfNull(labels);

        var sb = new StringBuilder();
        sb.Append("<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<title>").Append(Encode(labels.Title)).Append("</title>\n");
        sb.Append("<style>body{font-family:'Segoe UI Variable','Segoe UI','Microsoft YaHei UI',sans-serif;color:#1b1b1b;background:#f3f3f3;margin:24px}")
          .Append("h1{font-size:20px;font-weight:600}p{color:#5c5c5c;font-size:13px}table{border-collapse:collapse;background:#fff;width:100%;font-size:13px}")
          .Append("th,td{border-bottom:1px solid #e5e5e5;padding:6px 8px;text-align:left;vertical-align:top}th{color:#5c5c5c;font-weight:600}td.num{text-align:right;white-space:nowrap}</style>\n</head>\n<body>\n");
        sb.Append("<h1>").Append(Encode(labels.Title)).Append("</h1>\n");
        sb.Append("<p>").Append(Encode(labels.ScanTime)).Append(": ").Append(Encode(scanTime.ToLocalTime().ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture)))
          .Append(" · ").Append(rows.Count.ToString(CultureInfo.InvariantCulture)).Append(" · ").Append(Encode(labels.GeneratedBy)).Append("</p>\n");
        sb.Append("<table>\n<thead><tr>");
        foreach (var h in new[] { labels.Name, labels.Version, labels.Publisher, labels.Type, labels.InstallLocation, labels.Status, labels.IsRunning, labels.UninstallMethod, labels.DiskUsage })
        {
            sb.Append("<th>").Append(Encode(h)).Append("</th>");
        }

        sb.Append("</tr></thead>\n<tbody>\n");
        foreach (var r in rows)
        {
            sb.Append("<tr>");
            foreach (var v in new[] { r.Name, r.Version, r.Publisher, r.Type, r.InstallLocation, r.Status, r.IsRunning ? labels.Yes : labels.No, r.UninstallMethod })
            {
                sb.Append("<td>").Append(Encode(v ?? string.Empty)).Append("</td>");
            }

            sb.Append("<td class=\"num\">").Append(Encode(r.DiskUsageText ?? string.Empty)).Append("</td></tr>\n");
        }

        sb.Append("</tbody>\n</table>\n</body>\n</html>\n");
        return sb.ToString();
    }

    private static void AppendCsvLine(StringBuilder sb, IEnumerable<string?> fields)
    {
        var first = true;
        foreach (var field in fields)
        {
            if (!first)
            {
                sb.Append(',');
            }

            first = false;
            var value = field ?? string.Empty;
            if (value.Contains(',') || value.Contains('"') || value.Contains('\n') || value.Contains('\r'))
            {
                sb.Append('"').Append(value.Replace("\"", "\"\"", StringComparison.Ordinal)).Append('"');
            }
            else
            {
                sb.Append(value);
            }
        }

        sb.Append("\r\n");
    }

    private static string Encode(string value) => WebUtility.HtmlEncode(value);
}
